# server:
#   port: 8081
spring:
  application:
    name: Config-Default
   # data:
   #  mongodb:
   #    database: StudentInfo
   #    host: localhost
   #    port: 27017
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


 
